#!/bin/sh

# 功能: 生成deepin项目的源码包(dsc)
# 调用: /deepin.dsc/run [项目名]
# 前置: 位于项目检出目录

set -e

DEBIAN="$(dirname $(readlink -f $0))/debian"
PKG="$1"
CWD="$(pwd)"

echo "目标项目: $PKG"
echo "检出位置: $CWD"

copy_debian()
{
  if [ ! -d "${DEBIAN}/${PKG}" ]; then
    echo "致命错误: debian目录不存在!"
    exit 1
  fi

  echo "覆盖debian目录..."
  rm -rf "${CWD}/debian"
  cp -r "${DEBIAN}/${PKG}" "${CWD}/debian"
}

build_dsc()
{
  echo "构建源码包..."
  git-buildpackage -S -us -uc --git-ignore-new --git-ignore-branch
}

copy_debian
build_dsc
